# pico.toml - StelLang Package Manifest

[package]
name = "my_stellang_project"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
description = "A new StelLang project."

[dependencies]
# Add dependencies here, e.g.:
# cool_lib = "1.0.0"
