[package]
name = "stellang"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "stellang"
path = "src/main.rs"

[[bin]]
name = "pico"
path = "src/bin/pico.rs"

[[test]]
name = "operator_tests"
path = "tests/operator_tests.rs"
